const fs = require("fs");
const path = require("path");
const zlib = require("zlib");

const root = path.resolve(__dirname, "..");
const targetDataDir = path.join(root, "exam-prep-miniprogram/data");
const targetUtilsDir = path.join(root, "exam-prep-miniprogram/utils");
const bank = JSON.parse(fs.readFileSync(path.join(root, "exam-prep/questions-v1.json"), "utf8"));

fs.mkdirSync(targetDataDir, { recursive: true });
fs.mkdirSync(targetUtilsDir, { recursive: true });
for (const fileName of fs.readdirSync(targetDataDir)) {
    if (/^questions-v2-part-\d+\.js$/.test(fileName)) {
        fs.unlinkSync(path.join(targetDataDir, fileName));
    }
}

const partSize = 80;
const partNames = [];
for (let offset = 0; offset < bank.questions.length; offset += partSize) {
    const partName = `questions-v2-part-${String(partNames.length + 1).padStart(2, "0")}`;
    const questions = bank.questions.slice(offset, offset + partSize);
    const compressed = zlib.gzipSync(Buffer.from(JSON.stringify(questions)), { level: 9 });
    fs.writeFileSync(
        path.join(targetDataDir, `${partName}.js`),
        `// Generated by scripts/generate_exam_prep_miniprogram_assets.js\nmodule.exports = ${JSON.stringify(compressed.toString("base64"))};\n`
    );
    partNames.push(partName);
}

fs.writeFileSync(
    path.join(targetDataDir, "questions-v2.js"),
    `// Generated by scripts/generate_exam_prep_miniprogram_assets.js
const fflate = require("../utils/fflate");
const encodedParts = [
${partNames.map((name) => `    require("./${name}")`).join(",\n")}
];
const base64Chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
const base64Lookup = new Uint8Array(256);

for (let index = 0; index < base64Chars.length; index += 1) {
    base64Lookup[base64Chars.charCodeAt(index)] = index;
}

function decodeBase64(value) {
    const padding = value.endsWith("==") ? 2 : value.endsWith("=") ? 1 : 0;
    const bytes = new Uint8Array((value.length * 3 >> 2) - padding);
    let outputIndex = 0;

    for (let index = 0; index < value.length; index += 4) {
        const chunk =
            (base64Lookup[value.charCodeAt(index)] << 18) |
            (base64Lookup[value.charCodeAt(index + 1)] << 12) |
            (base64Lookup[value.charCodeAt(index + 2)] << 6) |
            base64Lookup[value.charCodeAt(index + 3)];
        if (outputIndex < bytes.length) bytes[outputIndex++] = chunk >> 16;
        if (outputIndex < bytes.length) bytes[outputIndex++] = chunk >> 8;
        if (outputIndex < bytes.length) bytes[outputIndex++] = chunk;
    }

    return bytes;
}

let questions = [];
for (const encodedPart of encodedParts) {
    const decodedPart = fflate.strFromU8(fflate.gunzipSync(decodeBase64(encodedPart)));
    questions = questions.concat(JSON.parse(decodedPart));
}

module.exports = { questions };
`
);
fs.copyFileSync(
    path.join(path.dirname(require.resolve("fflate/package.json")), "umd/index.js"),
    path.join(targetUtilsDir, "fflate.js")
);
fs.copyFileSync(
    path.join(root, "exam-prep/core.js"),
    path.join(targetUtilsDir, "core.js")
);

console.log(`generated mini program assets: ${bank.questions.length} questions`);