const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const targetDataDir = path.join(root, "exam-prep-miniprogram/data");
const targetUtilsDir = path.join(root, "exam-prep-miniprogram/utils");
const bank = JSON.parse(fs.readFileSync(path.join(root, "exam-prep/questions-v1.json"), "utf8"));

fs.mkdirSync(targetDataDir, { recursive: true });
fs.mkdirSync(targetUtilsDir, { recursive: true });
fs.writeFileSync(
    path.join(targetDataDir, "questions-v1.js"),
    `// Generated by scripts/generate_exam_prep_miniprogram_assets.js\nmodule.exports = ${JSON.stringify(bank)};\n`
);
fs.copyFileSync(
    path.join(root, "exam-prep/core.js"),
    path.join(targetUtilsDir, "core.js")
);

console.log(`generated mini program assets: ${bank.questions.length} questions`);